### ISSUE TITLE
bug-fix autoload.php not found

### ISSUE THREAD

**Issue by ACuriousSeaTurtle** [ACuriousSeaTurtle/SOEN341-SC4#12]
On a fresh clone, attempting to serve the page via "php artisan serve" generates:
"PHP Warning:  require(F:\users\Paul Lane\Downloads\GitHub\SOEN341--C4\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in F:\
users\Paul Lane\Downloads\GitHub\SOEN341-SC4\bootstrap\autoload.php on line 17"

**Comment by frodinm** [comment]
composer update --no-scripts solves this problem. We do need to run it after every fresh clones.

**Comment by ACuriousSeaTurtle** [comment]
I saw your solution, I preemptively created this issue in case I can make it so we don't need to run that after every fresh clone. If I can't do that, then I'll close the issue

**Comment by ACuriousSeaTurtle** [comment]
I have not found a way to correct this issue. A composer project must simply be updated by the command "composer update --no-scripts" when cloned from the repository
